# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    commands:
      - echo Installing NPM Global Dependencies...
      - npm install -g yarn
      - npm install -g pm2
      - REPOSITORY_URI=ssh://git-codecommit.us-east-2.amazonaws.com/v1/repos/rover-api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  pre_build:
    commands:
      - echo Installing client source NPM dependencies...
      - npm install
      - cd client && npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - pm2 startOrReload ./ecosystem.json --update-env
      - pm2 log rover-api --nostream --lines 25
      - pm2 show rover-api
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
# [TODO] Setup Mocha and finish this list...
artifacts:
  files:
    - server/index.js
    - client/build/index.html
    - package-lock.json
    - node_modules/dotenv/*
    - node_modules/express/*
    - node_modules/lodash/*
    - node_modules/ws/*
